-- ============================================
-- DOT VIDEO
-- LIKES + VIEWS + SHARE SETUP
-- ============================================

-- 1. Add Views and Likes columns
ALTER TABLE public.videos
ADD COLUMN IF NOT EXISTS views bigint NOT NULL DEFAULT 0;

ALTER TABLE public.videos
ADD COLUMN IF NOT EXISTS likes bigint NOT NULL DEFAULT 0;


-- 2. Table for one-like-per-user
CREATE TABLE IF NOT EXISTS public.video_likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id uuid NOT NULL
        REFERENCES public.videos(id)
        ON DELETE CASCADE,
    voter_id text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT video_likes_unique_user
        UNIQUE (video_id, voter_id),

    CONSTRAINT video_likes_voter_id_length
        CHECK (length(voter_id) BETWEEN 16 AND 128)
);


-- 3. Enable Row Level Security
ALTER TABLE public.video_likes ENABLE ROW LEVEL SECURITY;


-- ============================================
-- VIEWS FUNCTION
-- ============================================

CREATE OR REPLACE FUNCTION public.increment_video_views(
    p_video_id uuid
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    new_views bigint;
BEGIN

    UPDATE public.videos
    SET views = COALESCE(views, 0) + 1
    WHERE id = p_video_id
      AND published = true
    RETURNING views INTO new_views;

    IF new_views IS NULL THEN
        RAISE EXCEPTION 'Video not found or not published';
    END IF;

    RETURN new_views;

END;
$$;


-- ============================================
-- LIKE FUNCTION
-- ONE USER = ONE LIKE
-- ============================================

CREATE OR REPLACE FUNCTION public.like_video_once(
    p_video_id uuid,
    p_voter_id text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    new_likes bigint;
    inserted_count integer;
BEGIN

    IF length(p_voter_id) < 16
       OR length(p_voter_id) > 128 THEN
        RAISE EXCEPTION 'Invalid voter ID';
    END IF;


    IF NOT EXISTS (
        SELECT 1
        FROM public.videos
        WHERE id = p_video_id
          AND published = true
    ) THEN
        RAISE EXCEPTION 'Video not found or not published';
    END IF;


    INSERT INTO public.video_likes (
        video_id,
        voter_id
    )
    VALUES (
        p_video_id,
        p_voter_id
    )
    ON CONFLICT (video_id, voter_id)
    DO NOTHING;


    GET DIAGNOSTICS inserted_count = ROW_COUNT;


    IF inserted_count = 1 THEN

        UPDATE public.videos
        SET likes = COALESCE(likes, 0) + 1
        WHERE id = p_video_id
          AND published = true;

    END IF;


    SELECT likes
    INTO new_likes
    FROM public.videos
    WHERE id = p_video_id;


    RETURN COALESCE(new_likes, 0);

END;
$$;


-- ============================================
-- CHECK WHETHER USER ALREADY LIKED
-- ============================================

CREATE OR REPLACE FUNCTION public.has_video_like(
    p_video_id uuid,
    p_voter_id text
)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.video_likes
        WHERE video_id = p_video_id
          AND voter_id = p_voter_id
    );
$$;


-- ============================================
-- SECURITY
-- ============================================

REVOKE ALL ON FUNCTION public.increment_video_views(uuid)
FROM PUBLIC;

REVOKE ALL ON FUNCTION public.like_video_once(uuid, text)
FROM PUBLIC;

REVOKE ALL ON FUNCTION public.has_video_like(uuid, text)
FROM PUBLIC;


GRANT EXECUTE ON FUNCTION public.increment_video_views(uuid)
TO anon, authenticated;

GRANT EXECUTE ON FUNCTION public.like_video_once(uuid, text)
TO anon, authenticated;

GRANT EXECUTE ON FUNCTION public.has_video_like(uuid, text)
TO anon, authenticated;


-- ============================================
-- DONE
-- ============================================
